"""Type stubs for the pybind11 extension module.

pybind11 does not emit stubs, so this file is maintained by hand alongside
`python/src/bindings.cpp`. Keep the two in step: a signature that drifts here is
invisible at runtime and shows up only as a wrong type hint.
"""

from __future__ import annotations

import enum
from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

USE_TIME_AS_OFFSET: int

class CyclopsError(RuntimeError): ...

class ModelKind(enum.Enum):
    NORMAL = ...
    POISSON = ...
    LOGISTIC = ...
    CONDITIONAL_LOGISTIC = ...
    TIED_CONDITIONAL_LOGISTIC = ...
    EFRON_CONDITIONAL_LOGISTIC = ...
    CONDITIONAL_POISSON = ...
    SELF_CONTROLLED_CASE_SERIES = ...
    COX = ...
    COX_RAW = ...
    TIME_VARYING_COX = ...
    FINE_GRAY = ...

class PriorKind(enum.Enum):
    NONE = ...
    LAPLACE = ...
    NORMAL = ...
    BAR_UPDATE = ...
    JEFFREYS = ...

class ConvergenceKind(enum.Enum):
    GRADIENT = ...
    LANGE = ...
    MITTAL = ...
    ONE_STEP = ...
    ZHANG_OLES = ...

class SelectorKind(enum.Enum):
    AUTO = ...
    BY_PID = ...
    BY_ROW = ...

class AlgorithmKind(enum.Enum):
    CCD = ...
    MM = ...

class NormalizationKind(enum.Enum):
    STANDARD_DEVIATION = ...
    MAX = ...
    MEDIAN = ...
    Q95 = ...

class NoiseLevel(enum.Enum):
    SILENT = ...
    QUIET = ...
    NOISY = ...

class Precision(enum.Enum):
    FP64 = ...
    FP32 = ...

class ColumnFormat(enum.Enum):
    DENSE = ...
    SPARSE = ...
    INDICATOR = ...
    INTERCEPT = ...

class PriorOptions:
    kind: PriorKind
    variance: float
    use_cross_validation: bool
    exclude: list[int]
    force_intercept: bool
    kinds: list[PriorKind]
    variances: list[float]
    def __init__(self) -> None: ...

class FitOptions:
    max_iterations: int
    tolerance: float
    convergence: ConvergenceKind
    algorithm: AlgorithmKind
    initial_bound: float
    max_bound_count: int
    use_kkt_swindle: bool
    swindle_multiplier: int
    do_it_all: bool
    auto_search: bool
    fold: int
    cv_repetitions: int
    lower_limit: float
    upper_limit: float
    grid_steps: int
    starting_variance: float
    selector: SelectorKind
    min_cv_data: int
    sync_cv: bool
    noise: NoiseLevel
    threads: int
    seed: int
    reset_coefficients: bool
    retry_on_poor_blr_step: bool
    def __init__(self) -> None: ...

class FitResult:
    @property
    def covariate_ids(self) -> npt.NDArray[np.int64]: ...
    @property
    def coefficients(self) -> npt.NDArray[np.float64]: ...
    @property
    def log_likelihood(self) -> float: ...
    @property
    def log_prior(self) -> float: ...
    @property
    def return_flag(self) -> str: ...
    @property
    def iterations(self) -> int: ...
    @property
    def prior_info(self) -> str: ...
    @property
    def variance(self) -> list[float]: ...
    @property
    def cross_validation_info(self) -> str: ...
    @property
    def covariate_count(self) -> int: ...
    @property
    def fit_seconds(self) -> float: ...
    @property
    def converged(self) -> bool: ...

class ProfileInterval:
    @property
    def covariate_id(self) -> int: ...
    @property
    def lower(self) -> float: ...
    @property
    def upper(self) -> float: ...
    @property
    def evaluations(self) -> int: ...

class ProfileCurve:
    @property
    def points(self) -> npt.NDArray[np.float64]: ...
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    @property
    def derivatives(self) -> npt.NDArray[np.float64]: ...

class ModelData:
    @staticmethod
    def create(
        kind: ModelKind,
        precision: Precision = ...,
        silent: bool = ...,
    ) -> ModelData: ...
    def set_outcome(
        self,
        y: Sequence[float],
        time: Sequence[float] = ...,
        stratum_id: Sequence[int] = ...,
        row_id: Sequence[int] = ...,
    ) -> None: ...
    def add_covariates_csc(
        self,
        indptr: Sequence[int],
        row_indices: Sequence[int],
        values: Sequence[float],
        covariate_ids: Sequence[int],
        force_sparse: bool = ...,
    ) -> None: ...
    def add_dense_covariate(
        self, covariate_id: int, values: Sequence[float]
    ) -> None: ...
    def add_intercept(self) -> None: ...
    def set_offset_covariate(
        self, covariate_id: int, already_on_log_scale: bool = ...
    ) -> None: ...
    def make_dense(self, covariate_ids: Sequence[int]) -> None: ...
    def normalize(self, kind: NormalizationKind) -> npt.NDArray[np.float64]: ...
    def finalize(self) -> None: ...
    @property
    def is_finalized(self) -> bool: ...
    @property
    def kind(self) -> ModelKind: ...
    @property
    def precision(self) -> Precision: ...
    @property
    def row_count(self) -> int: ...
    @property
    def covariate_count(self) -> int: ...
    @property
    def stratum_count(self) -> int: ...
    @property
    def has_intercept(self) -> bool: ...
    @property
    def has_offset(self) -> bool: ...
    @property
    def intercept_label(self) -> int: ...
    @property
    def covariate_ids(self) -> npt.NDArray[np.int64]: ...
    @property
    def covariate_formats(self) -> list[ColumnFormat]: ...
    @property
    def outcome(self) -> npt.NDArray[np.float64]: ...
    @property
    def time(self) -> npt.NDArray[np.float64]: ...
    @property
    def stratum_index(self) -> npt.NDArray[np.int32]: ...
    @property
    def normal_based_default_variance(self) -> float: ...
    def univariable_correlation(
        self, ids: Sequence[int] = ...
    ) -> npt.NDArray[np.float64]: ...
    def column_sum(self, covariate_id: int, power: int = ...) -> float: ...
    def sum_by_stratum(
        self, covariate_id: int, power: int = ...
    ) -> npt.NDArray[np.float64]: ...

class Model:
    @staticmethod
    def create(data: ModelData, compute_device: str = ...) -> Model: ...
    def set_prior(self, prior: PriorOptions) -> None: ...
    def set_options(self, options: FitOptions) -> None: ...
    def set_weights(self, weights: Sequence[float]) -> None: ...
    def set_censor_weights(self, weights: Sequence[float]) -> None: ...
    def set_start_values(self, beta: Sequence[float]) -> None: ...
    def set_fixed(self, fixed: Sequence[bool]) -> None: ...
    def fit(self) -> FitResult: ...
    def predict(self) -> npt.NDArray[np.float64]: ...
    @property
    def log_likelihood(self) -> float: ...
    @property
    def log_prior(self) -> float: ...
    @property
    def coefficients(self) -> npt.NDArray[np.float64]: ...
    def gradient(self) -> npt.NDArray[np.float64]: ...
    def hessian_diagonal(
        self, ids: Sequence[int]
    ) -> npt.NDArray[np.float64]: ...
    def standard_errors(
        self, ids: Sequence[int] = ...
    ) -> npt.NDArray[np.float64]: ...
    def fisher_information(
        self, ids: Sequence[int] = ...
    ) -> npt.NDArray[np.float64]: ...
    def is_regularized(self) -> list[bool]: ...
    def profile(
        self,
        ids: Sequence[int],
        threads: int = ...,
        threshold: float = ...,
        include_penalty: bool = ...,
    ) -> list[ProfileInterval]: ...
    def profile_curve(
        self,
        covariate_id: int,
        points: Sequence[float],
        threads: int = ...,
        include_penalty: bool = ...,
        with_derivatives: bool = ...,
    ) -> ProfileCurve: ...
    def take_log(self) -> list[str]: ...

def version() -> str: ...
def list_gpu_devices() -> list[str]: ...
def removes_intercept(kind: ModelKind) -> bool: ...
def requires_strata(kind: ModelKind) -> bool: ...
def requires_time(kind: ModelKind) -> bool: ...
def requires_offset(kind: ModelKind) -> bool: ...
